### ISSUE TITLE
Sometimes appear - scrollViewDidScroll

### ISSUE THREAD

**Issue by Hacoga** [kimar/KIImagePager#34]
After leaving of a viewcontroller, appear this error.

[NewDetailViewController scrollViewDidScroll:]: message sent to deallocated instance 0x17624d80

Help.

Thanks.
Greetings from México

**Comment by kimar** [comment]
Hi, could you provide a sample code or stacktrace where this happens?

**Comment by Hacoga** [comment]
Apologies! the error is not on KIImagePager..
