### ISSUE TITLE
No photo cache ?

### ISSUE THREAD

**Issue by christopherney** [kimar/KIImagePager#46]
Hi,

Thank you for your job. 

Without SDWebImage I can use your component offline, because your class KIImagePagerDefaultImageSource not use a cache disk storage.

Do you have a solution ?

Thank you

**Comment by kimar** [comment]
Hi, just implement caching inside your app and return the images using `- (NSArray *) arrayWithImages:(KIImagePager*)pager;`.

https://github.com/kimar/KIImagePager/blob/master/KIImagePager/KIImagePager/KIImagePager.h#L20
