### ISSUE TITLE
arrayWithImages not loading array of images url/strings

### ISSUE THREAD

**Issue by saintjab** [kimar/KIImagePager#47]
#pragma mark - KIImagePager DataSource
- (NSArray *) arrayWithImages:(KIImagePager*)pager
{
    /*return @[
             //@"https://files.parsetfss.com/3cebf0c7-ae8f-4072-bb5a-ea8d98a64e87/tfss-2d805863-4caa-4317-aa75-b865759b4c79-Image.jpg",
             //@"https://files.parsetfss.com/3cebf0c7-ae8f-4072-bb5a-ea8d98a64e87/tfss-695d639d-e275-4226-be25-808cbe8f80e2-Image.jpg",
             //@"https://files.parsetfss.com/3cebf0c7-ae8f-4072-bb5a-ea8d98a64e87/tfss-5a4084bb-d5fe-4ce9-a0b6-3813f205acb0-Image.jpg"
             ];*/
    return imageURLs;
}
This method doesn't work though I am populating imageURLs with same URLs as in the commented lines. The commented lines work perfectly but I can't use that as I don't know the URLs before hand and hence I need to populate an array and return that.

**Comment by kimar** [comment]
Hi, did you try to return an instance object array and invoke `reloadData` on the pager?

E.g.

```
- (NSARRAY *) arrayWithImages:(KIImagePager)pager {
 return self.imageUrls;
}
```

and after getting your image urls:
```
self.imageUrls = ...
[self.myPage reloadData];
```

**Comment by saintjab** [comment]
Hi, that was a brilliant solution. Thank you very much. 

    On Tuesday, December 29, 2015 12:34 PM, Marcus Kida <notifications@github.com> wrote:
 

 Hi, did you try to return an instance object array and invoke reloadData on the pager?E.g.- (NSARRAY *) arrayWithImages:(KIImagePager)pager {
 return self.imageUrls;
}
and after getting your image urls:self.imageUrls = ...
[self.myPage reloadData];

**Comment by kimar** [comment]
You're welcome :+1:
