### ISSUE TITLE
Add array property.

### ISSUE THREAD

**Issue by NikKovV** [kimar/KIImagePager#54]
How about to add array property due to do something like this:

(void) imagePager:(KIImagePager )imagePager didSelectImageAtIndex:(NSUInteger)index
{
    AMFullScreenPhotoWithZoomViewController fullScrContr = [AMFullScreenPhotoWithZoomViewController new];
    fullScrContr.imagesArrayFullUrlString = **imagePager.array**;
    fullScrContr.fromIndexToStart = [NSNumber numberWithInt:imagePager.currentPage];
    [self.navigationController pushViewController:fullScrContr animated:YES];
}

**Comment by NikKovV** [comment]
Now i did it by delegate method of cell.

**Comment by kimar** [comment]
Exactly, just use the data source, that's the way to go:
`- (NSArray *) arrayWithImages:(KIImagePager*)pager;
`
