### ISSUE TITLE
Function to detect the image index when scrolling

### ISSUE THREAD

**Issue by JEKos** [kimar/KIImagePager#60]
Hi,
Which function is for detecting the images?
I mean, when it scrolling(auto or manual), print the index of the image , for example.
This image is the "2", 
This is image is the "3".

**Comment by JEKos** [comment]
Does this library has this function to recognize which photo is , when is scrolling?

**Comment by kimar** [comment]
Hi,

```
- (void) imagePager:(KIImagePager *)imagePager didScrollToIndex:(NSUInteger)index;
```

in `KIImagePagerDelegate` will be invoked in this scenario.
