### ISSUE TITLE
Stop the slide after you left from this screen

### ISSUE THREAD

**Issue by JEKos** [kimar/KIImagePager#62]
Hi,
There is any way to stop the slideshow after the user left from this screen with it ?
Something like kiimagepager.stop() or kiimagerpage.destroy()  ??

**Comment by hasyapanchasara** [comment]
You just need to do

```
ObjKImagePager.delegate = nil
ObjKImagePager.dataSource = nil

```
It will immediately stop everything for KImagePager.

If is is in UITableViewCell then you can do like 

```
let indexpath : NSIndexPath = NSIndexPath (row: 0 , section: 0)
        
let cell = tblObject.cellForRow(at: indexpath as IndexPath) as! UITableViewCustomCell
        
cell.BannerPage.delegate = nil
cell.BannerPage.dataSource = nil
```

**Comment by JEKos** [comment]
Oh, thank you!
